#!/bin/sh

mkdir -p build; cd build && CONAN_SYSREQUIRES_MODE=enabled conan install -c tools.system.package_manager:mode=install -c  tools.system.package_manager:sudo=True --update .. --build=missing  -s compiler.libcxx=libstdc++11 && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build  .

cpack

cp ./bin/r-type_client ../

cp ./bin/r-type_server ../